### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by Ryuuba** [camarenaS100/Conversiones_I_M#1]
Este repositorio no debe contener el código fuente de sus funciones; el objetivo es que un programador pueda utilizar su biblioteca únicamente mediante el código máquina de su software. Tampoco es necesario que el directorio `app` este en este repo, el programador sabrá dónde guardar su ejecutable. Esta última condición no está presente en los requisitos originales, pero conviene tenerla en cuenta.

El tutorial para usar la biblioteca es pobre, deben agregar ejemplos que ayuden al usuario a utilizar correctamente sus funciones.

No lo especifiqué en las restricciones de la tarea, pero podrían enriquecer la documentación de su cabecera agregando la anotación `@author`, la cual indica la identidad del autor del código. Pueden utilizar su matrícula o su ID de github para mantener anónima su identidad.

No puedo evaluar su proyecto porque no puedo enlazar el código de sus bibliotecas con el código de mi función `main`, ni en Windows ni en Linux. Los errores que obtengo se ilustran abajo. La hipótesis que tengo es que los errores se deben a que la compilación la hicieron utilizando el compilador clang de macOS, el cual yo no puedo utilizar. Por esta razón, les pido que vuelvan a compilar sus bibliotecas, pero esta vez usando el compilado de MinGW.

![image](https://user-images.githubusercontent.com/8430646/185508651-0e31d6f0-8854-43a7-833e-740d170170fe.png)

![linux](https://user-images.githubusercontent.com/8430646/185508781-9740c715-8165-4f66-90ae-beb0a1a4728d.png)

Les solicito que atiendan los comentarios que les hago en este documento. Tienen hasta la medianoche del domingo para hacer los cambios. Si modifican el repositorio fuera de esa fecha, entonces la actividad I7 se evaluará con cero. El cumplimiento de los comentarios aquí hechos garantiza el cumplimiento de los requisitos de la actividad I7.

**Comment by camarenaS100** [comment]
Ya debería funcionar @Ryuuba
